version: "3.9"

services:
  postgres:
    image: postgres:16-alpine # Используйте конкретную версию для стабильности
    container_name: 'mono-postgres'
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=krapassword
      - POSTGRES_USER=krakra
      - POSTGRES_DB=kra_db